---
name: Checks

on: [push]
jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secret.DOCKER_USER }}
          password: ${{ secret.DOCKER_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"


